[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nore_c"  # as it would appear on PyPI
version = "0.1.0"
authors = [
  {name = "Nore(C)"},
]

[tool.setuptools]
ext-modules = [
  {name = "nore_c", sources = ["foo.c"]}
]
