language: bash

matrix:
  include:
    - os: linux
    - os: osx

env:
  - SHELL=bash

before_script:
  - bash <(curl https://raw.githubusercontent.com/junjiemars/nore/master/bootstrap.sh)

script: 
  - ./.travis-tests.sh
