name: C

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - CC: "gcc"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build and Test
        run: |
          ./test.sh
          tar cvzf c-linux.tgz out/
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: c-linux.tgz
          path: out/c-linux.tgz

  # MacOS:
  #   runs-on: macos-latest
  #   strategy:
  #     matrix:
  #       include:
  #         - CC: "clang"

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Build and Test
  #       run: |
  #         ./test.sh

  # Windows:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       include:
  #         - CC: "cl"

  #   defaults:
  #     run:
  #       shell: msys2 {0}

  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0 # checkout history and tags

  #   - name: Install Dependencies
  #     uses: msys2/setup-msys2@v2
  #     with:
  #       update: true
  #       install: git make mingw-w64-x86_64-gcc mingw-w64-x86_64

  #   - name: Build and Test
  #     run: |
  #       CC=cl ./test.sh


# EOF
